import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  BorderStyle,
} from "docx";

/**
 * Convert plain-text letter (from Claude) into a professionally formatted Word document.
 * Returns a Buffer containing the .docx file.
 */
export async function generateLetterDocx(
  letterText: string,
  analysisId: number
): Promise<Buffer> {
  const lines = letterText.split("\n");

  const children: Paragraph[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (line.trim() === "") {
      // Empty line → spacing paragraph
      children.push(
        new Paragraph({
          text: "",
          spacing: { after: 80 },
        })
      );
      continue;
    }

    // Date line (starts with a month name or [Date])
    if (/^\[Date\]|^(January|February|March|April|May|June|July|August|September|October|November|December)/i.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 24, font: "Calibri" })],
          spacing: { after: 120 },
        })
      );
      continue;
    }

    // RE: subject line
    if (/^RE:|^Re:|^Subject:/i.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              bold: true,
              size: 24,
              font: "Calibri",
            }),
          ],
          spacing: { after: 160 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 1, color: "9C7E2E" },
          },
        })
      );
      continue;
    }

    // Salutation
    if (/^Dear /i.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 24, font: "Calibri" })],
          spacing: { after: 160 },
        })
      );
      continue;
    }

    // Closing lines
    if (/^(Sincerely|Respectfully|Best regards|Regards|Thank you),?$/i.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 24, font: "Calibri" })],
          spacing: { before: 240, after: 80 },
        })
      );
      continue;
    }

    // Placeholder signature lines like [Physician Name]
    if (/^\[Physician Name\]|\[Your Name\]/i.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              size: 24,
              font: "Calibri",
              italics: true,
              color: "666666",
            }),
          ],
          spacing: { after: 80 },
        })
      );
      continue;
    }

    // Numbered list items (1. 2. etc)
    if (/^\d+\.\s/.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line.trim(), size: 24, font: "Calibri" })],
          bullet: { level: 0 },
          spacing: { after: 80 },
          indent: { left: 360 },
        })
      );
      continue;
    }

    // Bullet items
    if (/^[-•]\s/.test(line.trim())) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line.trim().replace(/^[-•]\s/, ""),
              size: 24,
              font: "Calibri",
            }),
          ],
          bullet: { level: 0 },
          spacing: { after: 80 },
        })
      );
      continue;
    }

    // Default body paragraph
    children.push(
      new Paragraph({
        children: [new TextRun({ text: line, size: 24, font: "Calibri" })],
        spacing: { after: 120 },
        alignment: AlignmentType.LEFT,
      })
    );
  }

  // Footer disclaimer
  children.push(
    new Paragraph({ text: "", spacing: { before: 480 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by MedContractIntel\u2122 — medcontractintel.com",
          size: 18,
          font: "Calibri",
          color: "888888",
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      border: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "This document is a communication template only and does not constitute legal advice.",
          size: 18,
          font: "Calibri",
          color: "888888",
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
    })
  );

  const doc = new Document({
    creator: "MedContractIntel",
    title: `Contract Letter — Analysis #${analysisId}`,
    description: "Physician contract negotiation letter",
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 24,
            color: "0A1F14",
          },
          paragraph: {
            spacing: { line: 276 }, // 1.15 line spacing
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
